name: github_email_notify
version: 0.0.0-dev
description: Custom emails for your labels and repos you care about
author: Kevin Moore <kevmoo@google.com>
homepage: https://github.com/kevmoo/github_email_notify
environment:
  sdk: '>=1.11.0 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.14.0'
  crypto: '^0.9.0'
  github_hook: any
  shelf: '>=0.6.0 <0.7.0'
  angular2: ^2.0.0-alpha.26
  appengine: any
  browser: any
  firebase: { git: {url: https://github.com/firebase/firebase-dart, ref: 'e060f55'}}
  github: ^2.2.3+1
  googleapis: any
  googleapis_auth: any
  path: ^1.3.5
  shelf_appengine: {git: {url: https://github.com/dart-lang/shelf_appengine, ref: '58649948'}}
  source_gen: ^0.4.2
transformers:
- angular2:
    entry_points:
        - web/client_app.dart
    reflection_entry_points:
        - web/client_app.dart
